version: '3.7'

networks:
  qwiz_network:
    driver: bridge
  
services:
  sql_server:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql_server
    environment:
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=1
    restart: on-failure
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver/data:/var/opt/mssql/data
      - ./sqlserver/log:/var/opt/mssql/log

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on: [sql_server]
    ports:
      - "54321:54321"
    links:
      - sql_server
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on: [sql_server,backend]
    links:
      - backend
    restart: on-failure
