networks:
  qwiz_network:
    driver: bridge
  
services:
  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - ./configuration/redis.env
    command: /bin/sh -c "redis-server --appendonly yes --requirepass $$REDIS_HOST_PASSWORD"
    volumes:
      - ./volumes/redis_data:/data
    restart: always

  sql_server:
    image: postgres:latest
    container_name: sql_server
    env_file:
      - ./configuration/sql_server.env
    restart: always
    volumes:
      - ./volumes/sql_server:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./configuration/backend.env
    depends_on:
      sql_server:
        condition: service_healthy
    ports:
      - "54321:54321"
    links:
      - sql_server
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on: [redis, backend]
    links:
      - backend
      - redis
    restart: always

volumes:
  redis_data:
    driver: local