version: '3.7'

networks:
  qwiz_network:
    driver: bridge
  
services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes  --requirepass 'yourStrong(!)Password'
    volumes:
      - ./redis_data:/data
    restart: always

  sql_server:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql_server
    environment:
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=1
    restart: always
    volumes:
      - ./sqlserver/data:/var/opt/mssql/data
      - ./sqlserver/log:/var/opt/mssql/log

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on: [sql_server]
    ports:
      - "54321:54321"
    links:
      - sql_server
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on: [redis, backend]
    links:
      - backend
      - redis
    restart: always

volumes:
  redis_data:
    driver: local